# Generated by Django 3.0.4 on 2020-06-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19_app', '0003_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='u_id',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
