# Generated by Django 3.0.4 on 2020-06-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19_app', '0004_symptoms_u_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='location',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
