# Generated by Django 3.0.4 on 2020-06-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19_app', '0005_symptoms_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptoms',
            name='location',
        ),
    ]
