# Generated by Django 3.0.4 on 2020-06-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19_app', '0006_remove_symptoms_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptoms',
            name='breathing',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='chest_pain',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='cough',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='speech',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='taste',
        ),
        migrations.RemoveField(
            model_name='symptoms',
            name='tiredness',
        ),
        migrations.AddField(
            model_name='symptoms',
            name='age',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='bluish_lips',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='body_aches',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='chills',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='constant_pain',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='diarrhea',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='dry_cough',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='fatigue',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='loss_of_appetite',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='loss_of_smell',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='mucus',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='shortness_of_breath',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='sore_throat',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='stuffy_nose',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='sudden_confusion',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='trouble_breathing',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='symptoms',
            name='vomiting',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='fever',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='headache',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
