# Generated by Django 3.0.4 on 2020-06-07 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19_app', '0007_auto_20200607_1132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='symptoms',
        ),
    ]
