# Generated by Django 3.0.4 on 2020-06-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19_app', '0008_delete_symptoms'),
    ]

    operations = [
        migrations.CreateModel(
            name='symp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(default='SOME STRING', max_length=100)),
                ('fever', models.CharField(default='SOME STRING', max_length=100)),
                ('fatigue', models.CharField(default='SOME STRING', max_length=100)),
                ('dry_cough', models.CharField(default='SOME STRING', max_length=100)),
                ('loss_of_appetite', models.CharField(default='SOME STRING', max_length=100)),
                ('body_aches', models.CharField(default='SOME STRING', max_length=100)),
                ('shortness_of_breath', models.CharField(default='SOME STRING', max_length=100)),
                ('mucus', models.CharField(default='SOME STRING', max_length=100)),
                ('sore_throat', models.CharField(default='SOME STRING', max_length=100)),
                ('headache', models.CharField(default='SOME STRING', max_length=100)),
                ('chills', models.CharField(default='SOME STRING', max_length=100)),
                ('loss_of_smell', models.CharField(default='SOME STRING', max_length=100)),
                ('stuffy_nose', models.CharField(default='SOME STRING', max_length=100)),
                ('vomiting', models.CharField(default='SOME STRING', max_length=100)),
                ('diarrhea', models.CharField(default='SOME STRING', max_length=100)),
                ('trouble_breathing', models.CharField(default='SOME STRING', max_length=100)),
                ('constant_pain', models.CharField(default='SOME STRING', max_length=100)),
                ('bluish_lips', models.CharField(default='SOME STRING', max_length=100)),
                ('sudden_confusion', models.CharField(default='SOME STRING', max_length=100)),
                ('u_id', models.CharField(default='SOME STRING', max_length=100)),
            ],
        ),
    ]
